/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.empresa.vista;

import com.empresa.modelo.CargaCombustible;
import com.empresa.controlador.ControladorCombustible;
import com.empresa.controlador.DatosCompartidos;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class RegistroCargaForm extends javax.swing.JFrame {

    private ControladorCombustible controlador = new ControladorCombustible();
    /**
     * Creates new form RegistroCargaForm
     */
    public RegistroCargaForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFecha = new javax.swing.JTextField();
        txtLitros = new javax.swing.JTextField();
        txtKilometraje = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);
        getContentPane().add(txtFecha);
        txtFecha.setBounds(156, 44, 163, 22);
        getContentPane().add(txtLitros);
        txtLitros.setBounds(156, 78, 163, 22);
        getContentPane().add(txtKilometraje);
        txtKilometraje.setBounds(156, 118, 163, 22);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(156, 158, 163, 22);

        jLabel1.setText("Fecha ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(68, 47, 34, 16);

        jLabel2.setText("Litros ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(68, 81, 32, 16);

        jLabel3.setText("Kilometraje ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(68, 118, 63, 16);

        jLabel4.setText("Precio");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(68, 158, 33, 16);

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(156, 208, 88, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vehiculoregistro 500x500.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel5.setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
try {
        // Obtener datos ingresados por el usuario en los JTextField
        String fechaStr = txtFecha.getText();
        double litros = Double.parseDouble(txtLitros.getText());
        int kmActual = Integer.parseInt(txtKilometraje.getText());
        double precio = Double.parseDouble(txtPrecio.getText());

        // Convertir la fecha (si es necesario)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha = sdf.parse(fechaStr);

        // Crear la nueva carga de combustible
        CargaCombustible c = new CargaCombustible(fecha, litros, kmActual, precio);
       DatosCompartidos.agregarCarga(c);
        // Agregarla al controlador
        ControladorCombustible.agregarCarga(c);
        
        // Mostrar en consola para verificar
        System.out.println("Carga de combustible agregada: " + c);
        
        // Confirmar que se guardó correctamente
        JOptionPane.showMessageDialog(this, "Carga registrada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al registrar la carga: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCargaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCargaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCargaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCargaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCargaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtLitros;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
